name: gogoboom_flutter_common
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  gogoboom_flutter_core:
    git:
      url: https://github.com/gogogoboom/flutter-core.git
      ref: main
  flutter_beautiful_popup:
    git:
      url: git@github.com:gogogoboom/Flutter_beautiful_popup.git
      ref: master
#  gogoboom_flutter_core:
#    path: ../flutter-core
  #图片缓存
  cached_network_image: ^3.2.0
  #图片选择器
  image_picker: ^0.8.4+4
  #文件选择器
  file_picker: ^4.3.0
  #打开带有字符串的文件
  open_file: ^3.2.1
  # Media类型处理
  mime: ^1.0.1
  #绘制svg
  flutter_svg: ^1.0.0
  #指示器集合
  flutter_spinkit: ^5.1.0
  #toast消息
  fluttertoast: ^8.0.8
  #一个非常容易使用的吐司库
  bot_toast: ^4.0.1
  #消息红点
  badges: ^2.0.2
  #用于启动URL
  url_launcher: ^6.0.17
  #城市列表、联系人列表，索引&悬停。基于scrollable_positioned_list
  azlistview: ^2.0.0-nullsafety.0
  # 汉字转拼音
  lpinyin: ^2.0.3
  #屏幕适配
  flutter_screenutil: ^5.0.1+2
  #下拉刷新
  pull_to_refresh: ^2.0.0
  #不损失精度的情况下对十进制数进行计算
  decimal: ^2.0.1
  #监听键盘弹出
  flutter_keyboard_visibility: ^5.1.0
  #谷歌字体
  google_fonts: ^2.1.0
  #底部导航按钮
  persistent_bottom_nav_bar: ^4.0.2
  #底部弹窗
  modal_bottom_sheet: ^2.0.0
  #app内更新
  upgrader: ^3.11.1
  #文件系统访问
  path_provider: ^2.0.8
  #应用程序包信息的API
  package_info_plus: ^1.3.0
  #获取当前设备信息
  device_info_plus: ^3.2.0
  #分享应用程序内容
  share_plus: ^3.0.4
  #简单的动画库
  animate_do: ^2.0.0
  #漂亮的日志输出
  logger: ^1.1.0
  #uuid
  uuid: ^3.0.5
  #简单的缩小图像/内容小部件
  photo_view: ^0.13.0
  #保存图片到相册
  image_gallery_saver: ^1.7.1
  #提供用于处理JSON的Dart构建系统生成器
  json_serializable: ^6.1.3
  #定义json_serializable用于创建json序列化和反序列化代码的注释
  json_annotation: ^4.4.0
  #启动页生成
  flutter_native_splash: ^1.3.2
  #元组
  tuple: ^2.0.0
  #权限管理
  permission_handler: ^8.3.0
  #显示占位符图片
  transparent_image: ^2.0.0
  #侧滑
  flutter_slidable: ^1.1.0
  #internationalization
  intl: ^0.17.0
  #不推荐使用
  event_bus: ^2.0.0
  #图片压缩
  flutter_image_compress: ^1.1.0
  #视频压缩
  video_compress: ^3.1.0
  #二维码
  qr_flutter: ^4.0.0
  #二维码扫描
  qr_code_scanner: ^0.6.1
  #仿微信图片选择
  wechat_assets_picker: ^6.3.1
  #仿微信相机拍摄
  wechat_camera_picker: ^2.6.3
  #文字动画
  animated_text_kit: ^4.2.1
  #app内安装更新
  app_installer: ^1.1.0
  #代码规范检测
  #  lint: ^1.8.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
